rootProject.name = "vertex"
include("vertex-spring-boot")
include("vertex-spring-boot-starter")
include("vertex-web-spring-boot-starter")
include("vertex-web-test-spring-boot-starter")
include("vertex-actuator-spring-boot-starter")
include("vertex-data-simple-spring-boot-starter")
include("vertex-spring-boot-samples:vertex-spring-boot-sample-web")
include("vertex-spring-boot-samples:vertex-spring-boot-sample-websocket")
include("vertex-spring-boot-samples:vertex-spring-boot-sample-data-simple")
