#--debug=true
#logging.level.root=DEBUG
#server.port=10010
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
vertex.http.server.deployments.instances=2
vertex.http.server.deployments.threadingModel=VIRTUAL_THREAD
spring.threads.virtual.enabled=true
spring.main.keep-alive=true