#--debug=true
#logging.level.root=DEBUG
#server.port=10010
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
vertex.http.server.deployments.instances=2
vertex.http.server.deployments.threadingModel=VIRTUAL_THREAD
spring.threads.virtual.enabled=true
spring.main.keep-alive=true
spring.data.redis.repositories.enabled=false
spring.data.redis.host=bj-crs-hbcc149a.sql.tencentcdb.com
spring.data.redis.port=23110
spring.data.redis.password=v4u1E1NO1q4m9c
spring.data.jdbc.repositories.enabled=false
# https://github.com/Azure-Samples/quickstart-spring-data-jdbc-mysql
# https://juejin.cn/post/6906453629381804046
logging.level.org.springframework.jdbc.core=DEBUG
spring.datasource.url=jdbc:mysql://bj-cdb-rdilt32c.sql.tencentcdb.com:63649/?useSSL=false&useUnicode=true&characterEncoding=utf-8&noAccessToProcedureBodies=true&serverTimezone=UTC
spring.datasource.username=dev
spring.datasource.password=v4u1E1NO1q4m9c